// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0PDr1cmVGjinNIosoQhs22yHAYb5MxM4',
    appId: '1:791501340484:web:87fe0e381c466b12d0a111',
    messagingSenderId: '791501340484',
    projectId: 'stress-c953a',
    authDomain: 'stress-c953a.firebaseapp.com',
    storageBucket: 'stress-c953a.firebasestorage.app',
    measurementId: 'G-VF2DQF3TE4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIsfOoEkTWDYiiV9Qb2bjhcgCbrOonKcA',
    appId: '1:791501340484:android:b195a2fdb574ecb8d0a111',
    messagingSenderId: '791501340484',
    projectId: 'stress-c953a',
    storageBucket: 'stress-c953a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsz9OlaH1ym2svI_ko7MxCk9wSEsn_EUs',
    appId: '1:791501340484:ios:b64837c77cb405cdd0a111',
    messagingSenderId: '791501340484',
    projectId: 'stress-c953a',
    storageBucket: 'stress-c953a.firebasestorage.app',
    androidClientId: '791501340484-niblv6fljh2caq1d20nla9ptmoptatj8.apps.googleusercontent.com',
    iosClientId: '791501340484-bnublpadfo2brku32p64re5r17bifvph.apps.googleusercontent.com',
    iosBundleId: 'com.example.estres',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsz9OlaH1ym2svI_ko7MxCk9wSEsn_EUs',
    appId: '1:791501340484:ios:b64837c77cb405cdd0a111',
    messagingSenderId: '791501340484',
    projectId: 'stress-c953a',
    storageBucket: 'stress-c953a.firebasestorage.app',
    androidClientId: '791501340484-niblv6fljh2caq1d20nla9ptmoptatj8.apps.googleusercontent.com',
    iosClientId: '791501340484-bnublpadfo2brku32p64re5r17bifvph.apps.googleusercontent.com',
    iosBundleId: 'com.example.estres',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0PDr1cmVGjinNIosoQhs22yHAYb5MxM4',
    appId: '1:791501340484:web:e56b14f6606e677ed0a111',
    messagingSenderId: '791501340484',
    projectId: 'stress-c953a',
    authDomain: 'stress-c953a.firebaseapp.com',
    storageBucket: 'stress-c953a.firebasestorage.app',
    measurementId: 'G-77PZPK5F4X',
  );
}
